services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bundle exec rails s -b '0.0.0.0'
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - RAILS_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/store
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=store-db-1
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/post/gresql/postgres_data
volumes:
  postgres_data:

